Added versioning from CI

diff --git a/.github/workflows/release-stage.yaml b/.github/workflows/release-stage.yaml
--- a/.github/workflows/release-stage.yaml
+++ b/.github/workflows/release-stage.yaml
@@ -1,7 +1,10 @@
 on:
   workflow_call:
     inputs:
-      branch:
+      ref:
+        type: string
+        required: true
+      build-number:
         type: string
         required: true
 
@@ -11,19 +14,21 @@ jobs:
     steps:
       - name: debug
         run: |
-          echo "${{ inputs.branch }}"
+          echo "${{ inputs.ref }}"
           echo "${{ github.base_ref }}"
 
-  java-version:
+  pre-requisites:
     needs: debug-job
     runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}
     outputs:
       java-version: ${{ steps.get-java-version.outputs.java-version }}
+      is-snapshot: ${{ steps.get-is-snapshot.outputs.is-snapshot }}
     steps:
       - name: Checkout client
         uses: actions/checkout@v4
         with:
-          ref: ${{ inputs.branch }}
+          fetch-depth: 0
+          ref: ${{ inputs.ref }}
 
       - name: Get java version
         id: get-java-version
@@ -34,21 +39,50 @@ jobs:
         run: |
           echo ${{ steps.get-java-version.outputs.java-version }}
 
+      - name: Detect if snapshot
+        id: get-is-snapshot
+        shell: bash
+        run: |
+          # Getting previous commit
+          COMMIT_REF="HEAD~1"
+
+          # Checking if previous commit contains pom.xml. This should always return true
+          if ! git show "${COMMIT_REF}:pom.xml" &>/dev/null; then
+            echo "Error: pom.xml not found in commit ${COMMIT_REF}"
+            exit 1
+          fi
+
+          # Getting previous version
+          OLD_VERSIONS=$(git show "${COMMIT_REF}:pom.xml" |
+            sed -n 's/.*<revision>\([^<]*\)<\/revision>.*/\1/p')
+
+          # Getting current version
+          NEW_VERSIONS=$(sed -n 's/.*<revision>\([^<]*\)<\/revision>.*/\1/p' pom.xml)
+
+          # Compare the extracted versions. CI will not commit snapshot version.
+          if [[ "${OLD_VERSIONS}" != "${NEW_VERSIONS}" ]]; then
+            echo "is-snapshot='false'" >> $GITHUB_OUTPUT
+          else
+            echo "is-snapshot='true'" >> $GITHUB_OUTPUT
+          fi
+
   build:
     uses: ./.github/workflows/release.yaml
-    needs: java-version
+    needs: pre-requisites
     strategy:
       matrix:
         crypto-type: [bouncycastle, gnu]
     with:
-      java-version: ${{ needs.java-version.outputs.java-version }}
-      branch: ${{ inputs.branch }}
+      ref: ${{ inputs.ref }}
+      java-version: ${{ needs.pre-requisites.outputs.java-version }}
       crypto-type: ${{ matrix.crypto-type }}
+      is-snapshot: ${{ needs.pre-requisites.outputs.is-snapshot }}
     secrets: inherit
 
   aggregate-published-artifacts:
     uses: ./.github/workflows/aggregate-build.yaml
-    needs: [java-version, build]
+    needs: [pre-requisites, build]
     secrets: inherit
     with:
-      java-version: ${{ needs.java-version.outputs.java-version }}
+      java-version: ${{ needs.pre-requisites.outputs.java-version }}
+      is-snapshot: ${{ needs.pre-requisites.outputs.is-snapshot }}
